name: AxonOnnx CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang & Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.13.0'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install ONNX
        run: pip install numpy onnx onnxruntime
      - name: Install transformers
        run: pip install git+https://github.com/huggingface/transformers.git sentencepiece pillow torch tensorflow
      - name: Install mix dependencies
        run: mix deps.get
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: MIX_ENV=test mix do compile --warnings-as-errors, test
